#!/bin/bash
#SBATCH --job-name=MG-Kraken-Bwa-gd
#SBATCH --output=kraken_bwa_gd_Mixed50G_1i2.out
#SBATCH --error=kraken_bwa_gd_Mixed50G_1i2.err
#SBATCH --nodes=1
#SBATCH --ntasks=1
#SBATCH --cpus-per-task=12
#SBATCH -p nodo.q
#SBATCH -w clus12

export k=19 #$1 #k is 19 by default
export T=30 #$2 #T is 30 by default

echo "----------------------------------------------------------------------"
echo "Let's play metagenomics using as input data:"
echo " - SAMPLE: "
echo "   + Mixed species samples"
echo "   + Single-end reads" 
echo " - REFERENCES: Whole genomes"
echo "----------------------------------------------------------------------"


REF_PATH=/home/caos/bio-data/DATA/whole_genomes
BWA_INDEX=/home/caos/bio-data/DATA/whole_genomes/BWA_index
KRAKEN_SAMPLES=/home/caos/bio-data/Kraken_data/analysis_50/data_mixed

mkdir -p /tmp/epineda/bio-data/workdirMixedSpp50G/ 
WK_DIR=/tmp/epineda/bio-data/workdirMixedSpp50G 

cd ${WK_DIR}
cp ${BWA_INDEX}/*.fasta.* ${WK_DIR}/.

#He eliminat la part de kraken perque estem utilitzant la bd de 50Gb i ja tenim els fitxers generats

# Now we loop through the 6 mixed species samples and map each of them against all 110 whole genomes
for lib in {1..6}; do
time {

	# Reasignem el SAMPLE_PATH ja que el nou fitxer és el que genera kraken i que es troba al working directory
	SAMPLE_PATH=${KRAKEN_SAMPLES}

	OUTPUT_PATH=/home/pfc/epineda/TFG_Esteve/bio-data/OUTPUT/BWA/SingleEnd_AllReads/MixedSppLib50G/WholeGenomes/k${k}_T${T}/MixedSppLib${lib} #NEW
        gd_OUTPUT_PATH=/home/pfc/epineda/TFG_Esteve/bio-data/OUTPUT/g-d_algorithm/SingleEnd_AllReads/MixedSppLib50G/WholeGenomes/MixedSppLib${lib}       #NEW: sembla ser el path per guardar la sortida de l'algorisme gamma-delta

        mkdir -p $OUTPUT_PATH
        mkdir -p $gd_OUTPUT_PATH

        ls -d *fasta* | cut -d"." -f1 | uniq | while read -r genome; do
        	echo "Mapping MixedSppLib" $lib " to reference " $genome
        	echo "Mapping MixedSppLib" $lib " to reference " $genome >&2

                echo "Time consumed by BWA" >&2
                time /home/caos/bio-data/TOOLS/bwa-0.7.15/bwa mem -k ${k} -T ${T} -t 12 ${genome}.fasta ${SAMPLE_PATH}/MixedSppLib${lib}-R1_trim.fastq > ${WK_DIR}/map_file.sam #BWA: eina per mapejar els reads d'entrada amb els genomes de referència

                echo "Time consumed by SAMTools" >&2
                time /home/caos/bio-data/TOOLS/samtools-1.10/samtools view -t 12 -F2308 ${WK_DIR}/map_file.sam > ${OUTPUT_PATH}/${genome}_MixedSppLib${lib}_F2308.sam #SAMTools: eina per eliminar els reads que no s'han mapejat sobre cap referència
                rm ${WK_DIR}/map_file.sam
	done

        echo "Let's assign reads to species with the gamma-delta algorithm!"
        echo "Let's assign reads to species with the gamma-delta algorithm!">&2
        echo "Time consumed by the g-d algorithm">&2
        time /home/caos/bio-data/TOOLS/Python-3.7.9/python /home/caos/bio-data/TOOLS/g-d_algorithm/g-d_algorithm_3.6.py -r ${SAMPLE_PATH}/MixedSppLib${lib}-R1_trim.fastq -g 0.99 -d 0.98 -m ${OUTPUT_PATH}/ -o ${gd_OUTPUT_PATH}/BWA-k${k}-T${T}_g0.99-d0.98_MixedSppLib${lib}.csv

}

done

rm ${WK_DIR}/*fasta*

